version: 2
registries:
  nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/microsoft/index.json
    username: ${{secrets.PUBLISH_GH_USERNAME}}
    password: ${{secrets.PUBLISH_GH_TOKEN}}
updates:
- package-ecosystem: nuget
  directory: "/"
  registries:
    - nuget-github
  target-branch: feature/3.0
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
