# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Validate pull requests to master and dev branches.

pr:
  branches:
    include:
    - master
    - dev
    - feature/2.0
  paths:
    exclude:
        - .github/*
        - build/*
        - docs/*
        - pipelines/*
        - scripts/*
        - .gitignore
        - CONTRIBUTING.md
        - LICENSE.txt
        - Microsoft.Graph.Core.sln
        - README.md
        - THIRD PARTY NOTICES
        - appveyor.yml

trigger: none # disable triggers based on commits.

variables:
  PACKAGE_NAME: 'microsoft.graph.core'
  PROJECT_PATH: '.\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj'

pool:
  vmImage: windows-latest

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: 'Run CredScan'
  inputs:
    debugMode: false

- task: PowerShell@2
  displayName: 'Validate updated version'
  inputs:
    targetType: filePath
    filePath: 'scripts\ValidateUpdatedNugetVersion.ps1'
    arguments: '-packageName "$(PACKAGE_NAME)" -projectPath "$(PROJECT_PATH)"'
  enabled: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'

# windows-latest image removes this from windows 2022
- pwsh: .\sdkmanager "platforms;android-26"
  displayName: 'Install Xamarin dependencies'
  workingDirectory: $(ANDROID_HOME)\tools\bin\

- task: MSBuild@1
  displayName: 'Build solution to run unit test'
  inputs:
    configuration: debug
    clean: true

- task: VSTest@2
  displayName: 'Run enabled tests'
  inputs:
    testAssemblyVer2: |
      **/netcoreapp3.1/Microsoft.Graph.DotnetCore.Core.Test.dll
      !**/*TestAdapter.dll
      !**/obj/**
    diagnosticsEnabled: true
    configuration: debug
    searchFolder: 'tests'
    platform: AnyCPU
    otherConsoleOptions: '/Framework:.NETCoreApp,Version=v3.1'

