name: Validate Pull Request

on:
  workflow_dispatch:
  push:
    branches: [ 'feature/*', 'dev' ,'master' ]
  pull_request:
    branches: [ 'feature/*', 'dev' ,'master' ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-2019 # windows-latest does not currently support code-QL
    env:
      solutionName: Microsoft.Graph.Core.sln
      relativePath: ./src/Microsoft.Graph.Core
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1 # use msbuild due to dotnet commands not supporting some targets https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/227

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name : Nuget Restore
        run: msbuild -t:restore -m

      - name: Build Project
        run: msbuild ${{ env.solutionName }} -m

      - name: Test Project
        run: vstest.console.exe ./tests/Microsoft.Graph.DotnetCore.Core.Test/bin/Debug/netcoreapp3.1/Microsoft.Graph.DotnetCore.Core.Test.dll

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

